### PR TITLE
Addition of a long cowl version of the D-25 and slight balancing

### PR DESCRIPTION
**Pull request by TheKurgan**
Addition of a long cowl version of the D-25 Radial Engine with several paint schemes. 
This was created for me by Spanner a couple of years ago, I asked if I could give it to you to be part of KAX, and he agreed.
Minor balancing of weight, velCurve and atmCurve.

### CODE REVIEW

**Comment by Lisias** [comment]
Great! Thank you very much!

I'm recovering from a flu, but soon I will merge it, fix some minor issues on KAX and then I will release a new version.

What the license you want to use for your asset? The current models, sounds and textures are copyrighted by Keptin with a license to be used by KAX, so it can't be applied to your assets.

**Comment by TheKurgan** [comment]
The assets are from SpannerMonkey. He made them for KAX, but they never got released. I asked him if I could give them to you and he agreed.
So, you put whatever license on them you see fit :)

**Comment by Lisias** [comment]
Hi!

Can you pinpoint me some material to understand the atmosphereCurve,  atmCurve and velCurve nodes for the ModuleEnginesFX module?

I'm toying with the engines, and I think they need some polishing. The static thrust at rest is patetic, the craft needs to reach about 80 m/s for the engines get full thrust.

From where did you get the information to build your numbers?

Cheers!

**Comment by TheKurgan** [comment]
Yeah, I may have screwed them up a little... sorry, that is why I wanted you to test them before you released them.

I do not have any reference material to point you to sorry, and I have not played with the curves in a long time.

BUT if you want, try replacing the current velCurves with this one:

velCurve
{
key = 0 0.1 0 0
key = 0.024 0.18 9.3 9.3
key = 0.065 0.93 5.4 5.4
key = 0.1 1 0 0
key = 0.56 0.44 -3 -3
key = 0.8 0 0 0
}

This should give it almost full power shortly after the plane starts rolling.
________________________________

**Comment by Lisias** [comment]
I think I understood the reasoning for this initial values. You want to prevent the engine to provide thrust while it is still being ignited....

**Comment by TheKurgan** [comment]
Yeah, I think that is what I was doing... trying to make it so it had very little thrust at super low speeds, or at least until the prop animation had spun up.
I guess I never finished testing.
Sorry about that
________________________________

**Comment by TheKurgan** [comment]
That velCurve I posted above seems good.

**Comment by Lisias** [comment]
> Yeah, I think that is what I was doing... trying to make it so it had very little thrust at super low speeds, or at least until the prop animation had spun up. I guess I never finished testing. Sorry about that

Not a problem, not a problem at all. :)

The problem on that solution is that I can't full throttle before launch, something needed on aircraft carriers on the WW2.

I'm finding a lot of small things that need to be rebalanced... The engine's air intake is too high, for starters, An carburator works fine on lower atmosphere, but you need turbo chargers to get higher. I'm trying to simulate it using extra air intakes, but so I need to downplay a bit the internal intake.

I'm reading every piece of documentation I find on the wild about the ModuleEngineFX. I think I found something that can work on preventing thrust kicks on turning on the engines. (sometimes I think I should go back to use the Firespitter engine module...)

**Comment by Lisias** [comment]
I found no way out of the mess without your hack on the velCurve.

However, while trying and failing I learnt enough to have an idea: I think we can fix this problem by using a new Module.... 

I will pursue this solution on https://github.com/net-lisias-ksp/KAX/issues/8

**Comment by Lisias** [comment]
@TheKurgan , I found a way!

It's very complicated, so please read it with attention :D 

```
    MODULE
   {
        name = ModuleEnginesFX
       // yada yada yada
	useEngineResponseTime = true
	engineSpoolIdle = 0.01
	engineSpoolTime = 5.0
       // yada yada yada
   }
```

The values need some trimming, but I think this is the way.

Found this by accident, I would never be able to find this on purpose.... :D

**Pull request merged**
